pipeline:
  build:
    image: jekyll/jekyll
    commands:
      - mkdir _site
      - gem install bundler
      - bundle install
      - jekyll build

branches: master
when:
  event: [push, pull_request,tag]
