pipeline:
  build:
    image: jekyll/jekyll
    commands:
      - mkdir _site
      - gem install bundler
      - bundle install
      - jekyll build

  deploy:
    image: drillster/drone-rsync
    hosts: [ "lanre.wtf" ]
    source: _site
    target: ~/git.lanre.wtf
    recursive: true
    # delete: true
    secrets: [ rsync_key, rsync_user ]

branches: master
when:
  event: [push, pull_request,tag]
